name: Build and Push to Dockerhub

# Trigger on a Semantic Git Tag
on:
  push:
    tags:
      - '*.*.*'

# Jobs to run when the trigger matches.
jobs:
  push_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          no-cache: true
          tags: entropysynthetica/timeapi:${{ github.ref_name }}